### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by rasssta** [fondberg/easee_hass#100]
I'm getting this issue, every time, on HASS restart:

```
2021-02-16 11:35:40 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/easee/controller.py", line 376, in refresh_sites_state
    self.update_ha_state()
  File "/home/homeassistant/.homeassistant/custom_components/easee/controller.py", line 284, in update_ha_state
    entity.async_schedule_update_ha_state(True)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 438, in async_schedule_update_ha_state
    assert self.hass is not None
AssertionError

```

I'm running the latest version via HACS (on Raspberry PI OS).

Let me know if you need any additional information. Thanks in advance.

**Comment by rasssta** [comment]
Fixed in 0.9.27.
