### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by SVH-Powel** [fondberg/easee_hass#145]
I installed 0.9.34 this morning and found out it would not start. There was a error message about not able to log in. It was also not possible to configure the integration. So I deleted it and tried to install it new and fresh, but was not able to log in. I then installed the previous version, 0.9.33 and everything went smooth. Log in worked and configuring the integration worked as expected.

**Comment by astrandb** [comment]
@SVH-Powel What version of HA are you using? Anything relevant in HA log?

**Comment by SVH-Powel** [comment]
2021.9.7

No, nothing relevant in the log.

**Comment by astrandb** [comment]
We haven't seen this problem here.
It would be helpful if you could assist in debugging by sending us logs. Please enable full debug log of the integration by entering following in configuration.yaml, restart homeassistant and repeat the failing procedure.
```yaml
logger:
  default: warning
  logs:
    custom_components.easee: debug
    pyeasee: debug
```

**Comment by SVH-Powel** [comment]
I was able to solve it. But as said, this was not a problem with the previous version. And it would be easier if errors like this are presented to the end user :-)

`2021-10-04 12:06:34 DEBUG (MainThread) [pyeasee.easee] getting token for user: xxxxx@yyyyy
2021-10-04 12:06:37 ERROR (MainThread) [pyeasee.easee] Bad request service (400: {'errorCode': 727, 'errorCodeName': 'EmailNotVerified', 'type': None, 'title': 'Email address not verified', 'status': 400, 'detail': '[Empty in production]', 'instance': None, 'extensions': {}} https://api.easee.cloud/api/accounts/login)
2021-10-04 12:06:37 ERROR (MainThread) [custom_components.easee.controller] Authorization failed to easee
2021-10-04 12:06:37 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxx@yyyyy for easee
Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 245, in initialize
    await self.easee.connect()
  File "/usr/local/lib/python3.9/site-packages/pyeasee/easee.py", line 185, in connect
    await raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/pyeasee/easee.py", line 49, in raise_for_status
    raise AuthorizationFailedException(data)
pyeasee.exceptions.AuthorizationFailedException: {'errorCode': 727, 'errorCodeName': 'EmailNotVerified', 'type': None, 'title': 'Email address not verified', 'status': 400, 'detail': '[Empty in production]', 'instance': None, 'extensions': {}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/easee/__init__.py", line 34, in async_setup_entry
    await controller.initialize()
  File "/config/custom_components/easee/controller.py", line 257, in initialize
    raise Unauthorized from err
homeassistant.exceptions.Unauthorized: Unauthorized`
