### ISSUE TITLE
Invalid isoformat string: '2021-11-14T19:41:42.0904121Z

### ISSUE THREAD

**Issue by prilly-dev** [fondberg/easee_hass#150]
Seems there are some error showing up in my log.

`2021-11-14 20:42:04 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyeasee/utils.py", line 56, in __getitem__
    return datetime.fromisoformat(self._storage[key]).replace(tzinfo=timezone.utc)
ValueError: Invalid isoformat string: '2021-11-14T19:41:42.0904121Z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyeasee/utils.py", line 59, in __getitem__
    return datetime.strptime(self._storage[key], "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-11-14T19:41:42.0904121Z' does not match format '%Y-%m-%dT%H:%M:%SZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/easee/entity.py", line 192, in state_attributes
    attrs[key] = self.get_value_from_key(attr_key)
  File "/config/custom_components/easee/entity.py", line 245, in get_value_from_key
    value = self.data.state[second]
  File "/usr/local/lib/python3.9/site-packages/pyeasee/utils.py", line 61, in __getitem__
    return datetime.strptime(self._storage[key], "%Y-%m-%dT%H:%M:%S.000Z").replace(tzinfo=timezone.utc)
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-11-14T19:41:42.0904121Z' does not match format '%Y-%m-%dT%H:%M:%S.000Z'
`

**Comment by olalid** [comment]
Odd, I have a few of these in my log as well. Seems to happen if the data-stream (signalr) is disconnected and the HA component falls back to polling the API while it is trying to reconnect. And then specifically after calling the equalizer state API, so this is most likely the "latestPulse" parameter that the code is trying to interpret.
The time format that is being parsed, 2021-11-14T19:41:42.0904121Z is not a standard time format. It uses a 7(!) digit fraction of seconds, and the ISO format supports only 6 digits.
If I try calling the API now though, it returns no fractions at all, so maybe this was already fixed on the server side...
Please let us know if you see these errors again.

**Comment by olalid** [comment]
After discussions with Easee I feel it is best to change our code so that it can handle any number of fraction digits, we are ignoring them already, but we have not seen this specific case before.
So potential fix can be found here, it needs some testing before release...
https://github.com/fondberg/pyeasee/pull/59
