### ISSUE TITLE
If there are no schedules we should not spam the logs

### ISSUE THREAD

**Issue by fondberg** [fondberg/easee_hass#16]
2020-08-05 11:49:23 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.easee_charger_eh239897_basic_schedule fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 463, in async_device_update
    await self.async_update()  # type: ignore
  File "/config/custom_components/easee/sensor.py", line 456, in async_update
    self._state = self.get_value_from_key(self._state_key)
  File "/config/custom_components/easee/sensor.py", line 439, in get_value_from_key
    value = self.charger_data.schedule[second]
KeyError: 'id'

**Comment by tmjo** [comment]
See #17 and corresponding PR for the library.

**Comment by tmjo** [comment]
This issue is ok now, right? Close?

**Comment by tmjo** [comment]
Believe this is ok.
