### ISSUE TITLE
easee unavailable

### ISSUE THREAD

**Issue by thores81** [fondberg/easee_hass#209]
### Question

After updating HA to latest version my charger is unavailable. 

### What version of the integration are you using?

version": "0.9.44",

### Anything in the logs that might be useful for us?

```txt
Denne feilen stammer fra en tilpasset integrasjon.

Logger: homeassistant
Source: custom_components/easee/controller.py:421
Integration: Easee EV Charger (documentation, issues)
First occurred: 13:47:21 (152 occurrences)
Last logged: 16:18:08

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 421, in refresh_sites_state
    charger_data.state = site_state.get_charger_state(charger_id, raw=True)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/site.py", line 128, in get_charger_state
    return ChargerState(charger_data["chargerState"], raw)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/charger.py", line 56, in __init__
    data = {
TypeError: 'NoneType' object is not a mapping
```

### Additional information

I have tried restart HA and uninstall and install the component with no luck.

**Comment by olalid** [comment]
This is the same issue as: https://github.com/fondberg/easee_hass/issues/208

**Comment by olalid** [comment]
Solved in https://github.com/fondberg/easee_hass/pull/210
