### ISSUE TITLE
Integrations list issue 

### ISSUE THREAD

**Issue by Cptkex82** [fondberg/easee_hass#267]
### The problem

I tried installing using HACS and if i use the current version i cant add the integration using the menu. It just keeps refreshing the list and nothing can be installed. I found a workaround installing the old 0.9.46 version which made the integrations menu work and i could install it and configure it. 

I then updated to 0.9.48 and it vanished from the integrations page, but the sensor is still there, i dont know if its pulling data but it seems so, i will have to try that out when the car needs charging. The integrations list is now bugged again. It would seem that something in 0.9.48 is the problem. Note that im using the server on rasbian version (frontend?) and not HASSIO. I know its a lesser product but i want both the GUI on the same machine. 

I have installed Pyeasee and i can see help info so its installed.

### Version of Easee integration having the issue?

0.9.48

### Version of Home Assistant Core having the issue?

Frontend-version: 20221010.0 - latest

### Anything in the logs that might be useful for us?

```txt
I dont know if its related but you mentioned it being a async wrap, and i can find this error in the logs that i dont think was there before. I checked and i am running python 3.9

Logger: homeassistant.components.websocket_api.http.connection
Source: loader.py:287
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:58:51 (1 occurrences)
Last logged: 10:58:51

[1725946176] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 755, in handle_integration_descriptions
    connection.send_result(msg["id"], await async_get_integration_descriptions(hass))
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 287, in async_get_integration_descriptions
    custom_flows[integration.integration_type][integration.domain] = metadata
KeyError: 'hub'
```

**Comment by astrandb** [comment]
Home Assistant is developing very fast and there is a new release every month. We try to follow this development but stay at least one month behind the leading edge. So if you want to keep an old version of HA you must also refrain from updating this integration.
The error in the log above is due to new functionality  introduced in HA 2022.11

**Comment by Cptkex82** [comment]
i see. Does 0.9.46 work as well as 0.9.48 so i can just downgrade and stick to that version for now?

**Comment by astrandb** [comment]
Please have a look at the release notes at https://github.com/fondberg/easee_hass/releases
If you are happy with 0.9.46 in you setup you can stay on that version. But you will generally get a better experience if you can find a way to run with reasonable updated versions.

**Comment by Cptkex82** [comment]
well having the integrations functionality does outweight the cons ;) 

Thank you (tack!) for creating and maintaining this and for such a quick reply.
