### ISSUE TITLE
binary_sensor update fails

### ISSUE THREAD

**Issue by hmorkemo** [fondberg/easee_hass#280]
### The problem

Something is wrong with 'latestFirmware'.
My home-assistant.log file is filled with these error messages. They come every 5-10 minutes:
```
2023-03-04 15:39:11.113 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.easee_home_26675_update_available fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 548, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_device_update
    raise exc
  File "/config/custom_components/easee/entity.py", line 249, in async_update
    self._state = self._state_func(self.data.state)
  File "/config/custom_components/easee/const.py", line 454, in <lambda>
    < int(state["latestFirmware"]),
  File "/usr/local/lib/python3.10/site-packages/pyeasee/utils.py", line 55, in __getitem__
    if type(self._storage[key]) == str and validate_iso8601(self._storage[key]):
KeyError: 'latestFirmware'
2023-03-04 15:39:11.382 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.easee_home_26675_update_available fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 548, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_device_update
    raise exc
  File "/config/custom_components/easee/entity.py", line 249, in async_update
    self._state = self._state_func(self.data.state)
  File "/config/custom_components/easee/const.py", line 454, in <lambda>
    < int(state["latestFirmware"]),
  File "/usr/local/lib/python3.10/site-packages/pyeasee/utils.py", line 55, in __getitem__
    if type(self._storage[key]) == str and validate_iso8601(self._storage[key]):
KeyError: 'latestFirmware'

```

### Version of Easee integration having the issue?

0.9.48

### Version of Home Assistant Core having the issue?

2023.2.5

**Comment by olalid** [comment]
Yes, we are aware, same as https://github.com/fondberg/easee_hass/issues/279

**Comment by olalid** [comment]
Should be fixed by https://github.com/fondberg/easee_hass/pull/286
