### ISSUE TITLE
Easee integration stopped working - "AuthorizationFailedException"

### ISSUE THREAD

**Issue by lbovay** [fondberg/easee_hass#285]
### The problem

Hi,

I've been happily using this integration since january, but since march 26th my Easee integration is not able to receive any data. I still have access with my smartphone app on iOS, but nothing on home assistant, all entities show "unavailable".

I tried to delete and re-add the Easee integration, I can see my device, but all entities remain "unavailable". When I search "Easee" in the logs, I get a recurrent error with 1406 occurences !

I don't know where to look or what else to try from here :/

### Version of Easee integration having the issue?

easee-0.9.48

### Version of Home Assistant Core having the issue?

core-2023.3.6

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant
Source: custom_components/easee/controller.py:483
Integration: Easee EV Charger (documentation, issues)
First occurred: March 27, 2023 at 10:41:14 PM (1406 occurrences)
Last logged: 10:03:31 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyeasee/easee.py", line 145, in check_status
    await raise_for_status(response)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/easee.py", line 54, in raise_for_status
    raise AuthorizationFailedException(data)
pyeasee.exceptions.AuthorizationFailedException: {'message': 'Unauthorized'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 483, in refresh_sites_state
    charger_data.state = await charger_data.product.get_state(raw=True)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/charger.py", line 230, in get_state
    state = await (await self.easee.get(f"/api/chargers/{self.id}/state")).json()
  File "/usr/local/lib/python3.10/site-packages/pyeasee/easee.py", line 132, in get
    await self.check_status(response)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/easee.py", line 150, in check_status
    await raise_for_status(response)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/easee.py", line 54, in raise_for_status
    raise AuthorizationFailedException(data)
pyeasee.exceptions.AuthorizationFailedException: {'message': 'Unauthorized'}
```

### Additional information

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.3.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "armv7l",
    "timezone": "Europe/Zurich",
    "os_name": "Linux",
    "os_version": "5.15.90",
    "supervisor": "2023.03.2",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "easee": {
      "version": "0.9.48",
      "requirements": [
        "pyeasee==0.7.50"
      ]
    },
    "hacs": {
      "version": "1.31.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "mikrotik_router": {
      "version": "0.0.0",
      "requirements": [
        "librouteros>=3.2.0",
        "mac-vendor-lookup>=0.1.12"
      ]
    },
    "tesla_custom": {
      "version": "3.11.0",
      "requirements": [
        "teslajsonpy==3.8.0"
      ]
    },
    "lovelace_gen": {
      "version": "0.1.1",
      "requirements": [
        "jinja2"
      ]
    }
  },
  "integration_manifest": {
    "domain": "easee",
    "name": "Easee EV charger",
    "version": "0.9.48",
    "documentation": "https://github.com/fondberg/easee_hass",
    "issue_tracker": "https://github.com/fondberg/easee_hass/issues",
    "requirements": [
      "pyeasee==0.7.50"
    ],
    "config_flow": true,
    "codeowners": [
      "@fondberg",
      "@tmjo",
      "@olalid",
      "@astrandb"
    ],
    "iot_class": "cloud_push",
    "integration_type": "hub",
    "loggers": [
      "pyeasee"
    ],
    "is_built_in": false
  },
  "data": {
    "account": {
      "username": "**REDACTED**",
      "password": "**REDACTED**"
    },
    "data": {
      "manufacturer": "Easee",
      "model": "Charging Robot"
    }
  }
}

**Comment by olalid** [comment]
The error messages seems to imply that it has not successfully logged in.
I have seen other cases where the user have had to change the password to get the integration working, so perhaps try that?

**Comment by lbovay** [comment]
Hi, thank you for the suggestion.

I just changed my password and tried to delete and re-add the integration to no avail. Entities still show as “unavailable” and the log shows the same “unauthorized” entry.

If I try to login with a wrong password the login is refused and asks me to login again. So the login part seems to work, but then it seems it cannot pull any information from the api.

many other ideas ?

**Comment by olalid** [comment]
Ok, all that I can say from the information you have provided is that the cloud does not see you as an authorised user to retrieve the state of the charger. I.e. at startup we call the /api/chargers/{self.id}/state to get the initial state of the charger, and the cloud responds saying that you are not authorised to retrieve that information.
Normally this would be either because the user you are logging in with is not the owner of that charger or because of a misconfiguration in the Easee cloud somehow.
We have seen before that changing password or making sure that the e-mail address is verified helps in some cases (you should have received some verification e-mail when you registered I think, where you need to respond somehow, was a long time since I did this myself...).

You can also try asking Easee if they can see something strange with your account that would stop the HA integration from working.

**Comment by cnrd** [comment]
I am seeing the same issue, chargers that I had access to before now shows as unavailable.

Same exception in the log.

I have access in the iOS app, and also have access to change settings on the chargers.

Looking at the site roles on the Easee website, I am showing up as a “Site User” for the site I am trying to access, not sure if that is related to the issue?

**Comment by olalid** [comment]
@cnrd and @lbovay, can you send me the ID(s) of the chargers you can not access so I can discuss it with Easee?
If you send it in an e-mail olal (a) plea.se ?

You are both sure you have done the e-mail verification step?

**Comment by lbovay** [comment]
Thank you for your feedback.

I can’t find a way to check if my e-mail has been verified, but I may have done it if it’s part of the registration process.

I’ll send you an email with the charger ID.

**Comment by olalid** [comment]
I have unfortunately no clue how to check if you did the e-mail verification.
Maybe you can see something in your account setting if you log in to easee cloud?

We have seen similar problems with other users who did not do this step.
Typically the app and the cloud login works fine, but for some reason the HA integration fails.
Once they fixed this, it started working again, but I never saw a detailed description about what they did to fix it.

Typically you will receive an e-mail during the installation procedure where you have to click on some link to verify the e-mail. I can easily find this e-mail in my e-mail history, but that will of course not tell me anything about if I clicked on the link or not...

**Comment by lbovay** [comment]
Answer from Easee support:
"I believe this is because you are linked to the site as a site User rather than a site Admin.
 
Please can you ask the site owner, or site admin to increase your privileges by giving you admin access?
 
At this point you will be able to get the state on all chargers linked to the site without issue. I believe site users are only able to control chargers in regards to start and stop rather than making any changes or getting historical data."

I can confirm that commands like start/stop/pause/resume still work. Which should be enough if I change my logic base actions on my car instead of the charger itself.

I will check with the site admin/owner if they can increase my privileges by giving me admin access. Nevertheless it feels odd that I can see the charger status on my mobile app but am denied authorization via the API. I'm not sure why the authorizations need to differ between the mobile app and the API.

**Comment by olalid** [comment]
But user priveligies should be enough to retrieve status, at least that is my impression from earlier.
I have not received any response from Easee yet on my query, I will try to remind them...

In any case, I am working on removing that API call, there is a newer API that Easee seems to prefer that we use, so perhaps that will help. It will be a while before I complete that change though since it has some implications on the general structure of the code.

**Comment by cnrd** [comment]
I just played around with the api.

it seems like the chargers/{id}/state endpoint returns a 401, but all the other non deprecated endpoints I tried returned data.

However I can’t seem to find a single endpoint that will return the current state of the charger.

**Comment by lbovay** [comment]
> But user priveligies should be enough to retrieve status, at least that is my impression from earlier.

Yes, and until March 26th I can see the charger state in my logs: so it was definitely working. Now it’s a bit tricky to know if there was a software update (firmware or api) that changed something or if perhaps I had admin privileges prior to March 26th. I remember I could see all chargers of the site at some point (they would appear as devices), but I never tried to access any other one but my own.

The fact is I live in an apartment block and there are about 30/40 Easee chargers operated by our local electricity provider. So the charger is mine, but operated by a 3rd party that is managing that charger site, I doubt they will give me privileges that would allow me to mess with other chargers :/

Let’s see, otherwise I hope the new API implementation will resolve this issue :)

**Comment by olalid** [comment]
Yes, agree, this has been working. They must have changed something on the server side that affects people in your situation.

That things with you seeing all the chargers on the site is something we changed a while back. Now we only create sensors for the chargers/equalizers that the user has added to the app.

I hope I will get some time during easter to work on the changes.

**Comment by olalid** [comment]
Please try the latest version and give us feedback if problem is solved or not.

**Comment by cnrd** [comment]
Yep everything is working 👍 thanks!

**Comment by lbovay** [comment]
> Please try the latest version and give us feedback if problem is solved or not.

Yes I get a status now. I'll re-enable my automations and check more in detail when I'm home. Thanks for that. Very quick reaction time 👍🏻

**Comment by lbovay** [comment]
> > Please try the latest version and give us feedback if problem is solved or not.
> 
> Yes I get a status now. I'll re-enable my automations and check more in detail when I'm home. Thanks for that. Very quick reaction time 👍🏻

Okay everything looks good. You can close this point as far as I'm concerned 👍🏻
