### ISSUE TITLE
Cannot load integration since 0.9.47

### ISSUE THREAD

**Issue by mnorrsken** [fondberg/easee_hass#308]
### The problem

Last version of easee hass that works is 0.9.46. If i load other versions i get errors:
```
2023-04-24 13:36:54.367 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration easee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-24 13:37:25.183 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.easee
File "/config/custom_components/easee/__init__.py", line 10, in <module>
File "/config/custom_components/easee/const.py", line 84, in <module>
2023-04-24 13:37:25.188 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration easee: Unable to import component: Exception importing custom_components.easee
```

### Version of Easee integration having the issue?

v0.9.50

### Version of Home Assistant Core having the issue?

2023.4.6

### Anything in the logs that might be useful for us?

```txt
2023-04-24 13:36:54.367 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration easee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-24 13:37:25.183 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.easee
File "/config/custom_components/easee/__init__.py", line 10, in <module>
File "/config/custom_components/easee/const.py", line 84, in <module>
2023-04-24 13:37:25.188 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration easee: Unable to import component: Exception importing custom_components.easee
```

### Additional information

0.9.47  (and 0.9.48) logs:
```
2023-04-24 13:45:32.766 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration easee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-24 13:46:02.498 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration easee: Unable to import component: cannot import name 'ForbiddenServiceException' from 'pyeasee.exceptions' (/config/deps/lib/python3.10/site-packages/pyeasee/exceptions.py)
```

**Comment by olalid** [comment]
Hi, I think there should be more lines in your log file, adjacent to those ones that you have included that might help us to understand what is going on in your installation.
I.e. Typically when you have an error like:
File "/config/custom_components/easee/const.py", line 84, in <module>
there would be line(s) after that describing the error in more detail.
Can you please look for that?

It kind of looks like your pyeasee lib installation is somehow damaged though, but hard to tell for sure...

**Comment by mnorrsken** [comment]
Here it is:
```
2023-04-24 15:07:25.112 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.easee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 760, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/easee/__init__.py", line 10, in <module>
    from .const import DOMAIN, LISTENER_FN_CLOSE, MIN_HA_VERSION, PLATFORMS, VERSION
  File "/config/custom_components/easee/const.py", line 84, in <module>
    ChargerStreamData.state_eqAvailableCurrentP1.value,
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: state_eqAvailableCurrentP1
```

**Comment by mnorrsken** [comment]
It looks like im having pyeasee version 0.7.44, even if easee_hass requires how can i update this? manifest.json seems to specify 0.7.52 but this is ignored??

**Comment by astrandb** [comment]
Home Assistant should normally update the requirements automatically. What type of installation of HA are you using? HAOS or manually managed core or some other variant?

**Comment by mnorrsken** [comment]
HAOS on Odroid N2+. I deleted the old libs from where i found them and restarted, now it seems to have downloaded the correct version and is working. I will check if its a permission problem or something like that after I restored my home assistant from a backup.
