### ISSUE TITLE
Energy/power sensor is unknown

### ISSUE THREAD

**Issue by jakobschou** [fondberg/easee_hass#331]
### The problem

I have gotten the Easee integration to work really well, and I am able to charge and monitor lifetime energy usage.
But one of the sensor which is showing the actual power draw is "Unknown" in HA, even when it is charging.

Why is that?

### Version of Easee integration having the issue?

2023.4.6

### Version of Home Assistant Core having the issue?

2023.4.6

**Comment by olalid** [comment]
I don't know :)
I take it you mean that the sensor is available, but the value is unknown?
Can you see any error or warning messages in the logs related to Easee?

**Comment by jakobschou** [comment]
Well it has been like that since I installed the integration.

I thought it was because it wasn't charging, but even when charging, it does not change.

I have enabled debug logging in the HA ui and added the logging line to my configuration.yaml - but how can I share the log?

**Comment by olalid** [comment]
You can send the log file to me at olal (a) plea.se if you want to send the complete file.

**Comment by jakobschou** [comment]
I might have found some of the log that might cause the error (by searching for pyeasee in the home-assistant.log):

`Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 651, in refresh_sites_state
    await charger_data.async_refresh()
  File "/config/custom_components/easee/controller.py", line 185, in async_refresh
    observations = await self.product.get_observations(*self.poll_observations)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/charger.py", line 197, in get_observations
    return await (await self.easee.get(f"/state/{self.id}/observations?ids={observation_ids}", base=1)).json()
  **File "/usr/local/lib/python3.10/site-packages/pyeasee/easee.py", line 131, in get
    response = await self.session.get(f"{self.base[base]}{url}", headers=self.headers, **kwargs)**
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.easee.com:443 ssl:default [Try again]
2023-05-24 04:02:08.410 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f41cdd5d0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player?additional_types=episode
2023-05-24 04:02:08.673 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-05-24 04:02:13.391 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_jakob_schou is taking over 10 seconds
2023-05-24 04:02:14.023 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b3d0e50>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player?additional_types=episode
2023-05-24 04:02:18.675 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-05-24 04:02:20.235 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f423bebc0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player?additional_types=episode
2023-05-24 04:02:26.455 WARNING (Thread-4 (_listen)) [homeconnect.sseclient] Exception while reading event: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/homeconnect/sseclient.py", line 81, in __next__
    next_chunk = next(self.resp_iterator)
StopIteration`

**Comment by olalid** [comment]
Well, this indicates that the api server does not respond when the initial polling of states happens.
But this is *only* done at startup. After that data is streamed over a SignalR.
If the initial poll does not work, it just means that sensors will have unknown state until there are new values available.
So if the other sensors are updating, I doubt that this is the main issue.

Did you enable the debug logging for the Easee component? Because I am not seeing any printouts from it here, this is just what python by default outputs when things go wrong.

Are you using v0.9.52?
