### ISSUE TITLE
Easee integration stopped working after HA update to 2023.6.2

### ISSUE THREAD

**Issue by WeirdSience** [fondberg/easee_hass#336]
### The problem

After updating Home Assistant to 2023.6.2 and Home Assistant OS to 10.3 the Easee intregration stopped working.

### Version of Easee integration having the issue?

?

### Version of Home Assistant Core having the issue?

2023.6.2

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.config_entries
Source: custom_components/easee/entity.py:115
Integration: Easee EV Charger (documentation, issues)
First occurred: 15:37:21 (1 occurrences)
Last logged: 15:37:21

Error unloading entry +46xxxxxxxxx for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 543, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 196, in async_unload_entry
    await platform.async_reset()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 763, in async_reset
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 872, in async_remove
    await self.async_will_remove_from_hass()
  File "/config/custom_components/easee/entity.py", line 115, in async_will_remove_from_hass
    ent_reg = await entity_registry.async_get_registry(self.hass)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.helpers.entity_registry' has no attribute 'async_get_registry'
```

**Comment by WeirdSience** [comment]
Easee integration needed an update then it worked fine
